apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-python-basic-dk27
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-python-basic-dk27
    app.kubernetes.io/part-of: test-app-nsgf
  name: devfile-sample-python-basic-dk27
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: devfile-sample-python-basic-dk27
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: devfile-sample-python-basic-dk27
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/build-e2e-ycbt-tenant/test-app-nsgf/devfile-sample-python-basic-dk27@sha256:abb5e7602e07d84bd266bb9c3be15f339f620de664c6798f3019632c287ceba0
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
